version: "3"
services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=password"
  minio:
    image: minio/minio:latest
    command: minio server --console-address ":9001" /home/shared
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres-data: