version: 1

goos: windows
goarch: amd64

main: ./cmd/client/main.go
binary: go-keeper-client-{{ .Os }}-{{ .Arch }}.exe

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

ldflags:
  - "-w"
  - "-s"
  - "-extldflags \"-static\""
  - "-X main.version={{ .Env.VERSION }}"
